version: '2'
services:
  zookeeper:
    image: zookeeper:latest
  kafka:
    image: wurstmeister/kafka
    environment:
      HOSTNAME_COMMAND: hostname
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "raw:2:2,preprocessed:2:2,decision:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  python:
    build: .
    image: bdp:latest
    volumes:
      - ./src/:/bdp/    
