version: '2'
services:
  zookeeper:
    image: zookeeper:latest
  kafka:
    image: wurstmeister/kafka
    environment:
      DEBUG_SUSPEND_FLAG: y
      HOSTNAME_COMMAND: hostname
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "raw:2:2,preprocessed:2:2,decision:1:1,flagged:2:2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5005
  kafka_2:
    image: wurstmeister/kafka
    environment:
      DEBUG_SUSPEND_FLAG: y
      HOSTNAME_COMMAND: hostname
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5005
  python:
    build: .
    image: bdp:latest
    volumes:
      - ./src/:/bdp/    
